// <auto-generated />
using System;
using FoodStore_mvc.Models.FoodStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodStore_mvc.Migrations
{
    [DbContext(typeof(FoodStoreContext))]
    partial class FoodStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Building", b =>
                {
                    b.Property<string>("BuildingName")
                        .HasColumnName("building_name")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("UnitNum")
                        .HasColumnName("unit_num");

                    b.Property<int?>("Capacity")
                        .HasColumnName("capacity");

                    b.HasKey("BuildingName", "UnitNum")
                        .HasName("PK__Building__14E071A0CB93A857");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnName("employee_id");

                    b.Property<string>("Branch")
                        .HasColumnName("branch")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("EmployeeId");

                    b.HasIndex("Branch");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Invoice", b =>
                {
                    b.Property<int>("InvoiceNum")
                        .HasColumnName("invoiceNum");

                    b.Property<string>("Branch")
                        .HasColumnName("branch")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("InvoiceNum")
                        .HasName("PK__Invoice__F9EE1383938C89D4");

                    b.HasIndex("Branch");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Manufacturer", b =>
                {
                    b.Property<string>("Mfg")
                        .HasColumnName("mfg")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<decimal?>("MfgDiscount")
                        .HasColumnName("mfgDiscount")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Mfg")
                        .HasName("PK__Manufact__DF50190DF6A5C524");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnName("productID");

                    b.Property<string>("Mfg")
                        .HasColumnName("mfg")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<decimal?>("Price")
                        .HasColumnName("price")
                        .HasColumnType("money");

                    b.Property<string>("Vendor")
                        .HasColumnName("vendor")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("ProductId");

                    b.HasIndex("Mfg");

                    b.HasIndex("Vendor");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.ProductInvoice", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnName("productID");

                    b.Property<int>("InvoiceNum")
                        .HasColumnName("invoiceNum");

                    b.HasKey("ProductId", "InvoiceNum")
                        .HasName("PK__ProductI__028E3072E4210938");

                    b.HasIndex("InvoiceNum");

                    b.ToTable("ProductInvoice");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.ProductInvoiceWithQuantity", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnName("productID");

                    b.Property<int>("InvoiceNum")
                        .HasColumnName("invoiceNum");

                    b.Property<int?>("Quantity")
                        .HasColumnName("quantity");

                    b.HasKey("ProductId", "InvoiceNum")
                        .HasName("PK__ProductI__028E3072658FC761");

                    b.HasIndex("InvoiceNum");

                    b.ToTable("ProductInvoiceWithQuantity");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.ProductPurchaseOrder", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnName("productID");

                    b.Property<int>("PoNum")
                        .HasColumnName("po_num");

                    b.HasKey("ProductId", "PoNum")
                        .HasName("PK__ProductP__6DEC0407F891FA0E");

                    b.HasIndex("PoNum");

                    b.ToTable("ProductPurchaseOrder");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.PurchaseOrder", b =>
                {
                    b.Property<int>("PoNum")
                        .HasColumnName("po_num");

                    b.Property<string>("Branch")
                        .HasColumnName("branch")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("PoNum")
                        .HasName("PK__Purchase__0FCD54D5F13621BE");

                    b.HasIndex("Branch");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Store", b =>
                {
                    b.Property<string>("Branch")
                        .HasColumnName("branch")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("BuildingName")
                        .HasColumnName("building_name")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Region")
                        .HasColumnName("region")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int?>("UnitNum")
                        .HasColumnName("unit_num");

                    b.HasKey("Branch")
                        .HasName("PK__Store__1F8431240463D376");

                    b.HasIndex("BuildingName", "UnitNum");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Supplier", b =>
                {
                    b.Property<string>("Vendor")
                        .HasColumnName("vendor")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("SupplierEmail")
                        .HasColumnName("supplier_email")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Vendor")
                        .HasName("PK__Supplier__42A1EB1C928D5FA1");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Employee", b =>
                {
                    b.HasOne("FoodStore_mvc.Models.FoodStore.Store", "BranchNavigation")
                        .WithMany("Employee")
                        .HasForeignKey("Branch")
                        .HasConstraintName("FK__Employee__branch__4316F928");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Invoice", b =>
                {
                    b.HasOne("FoodStore_mvc.Models.FoodStore.Store", "BranchNavigation")
                        .WithMany("Invoice")
                        .HasForeignKey("Branch")
                        .HasConstraintName("FK__Invoice__branch__31EC6D26");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Product", b =>
                {
                    b.HasOne("FoodStore_mvc.Models.FoodStore.Manufacturer", "MfgNavigation")
                        .WithMany("Product")
                        .HasForeignKey("Mfg")
                        .HasConstraintName("FK__Product__mfg__286302EC");

                    b.HasOne("FoodStore_mvc.Models.FoodStore.Supplier", "VendorNavigation")
                        .WithMany("Product")
                        .HasForeignKey("Vendor")
                        .HasConstraintName("FK__Product__vendor__29572725");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.ProductInvoice", b =>
                {
                    b.HasOne("FoodStore_mvc.Models.FoodStore.Invoice", "InvoiceNumNavigation")
                        .WithMany("ProductInvoice")
                        .HasForeignKey("InvoiceNum")
                        .HasConstraintName("FK__ProductIn__invoi__35BCFE0A");

                    b.HasOne("FoodStore_mvc.Models.FoodStore.Product", "Product")
                        .WithMany("ProductInvoice")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ProductIn__produ__34C8D9D1");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.ProductInvoiceWithQuantity", b =>
                {
                    b.HasOne("FoodStore_mvc.Models.FoodStore.Invoice", "InvoiceNumNavigation")
                        .WithMany("ProductInvoiceWithQuantity")
                        .HasForeignKey("InvoiceNum")
                        .HasConstraintName("FK__ProductIn__invoi__398D8EEE");

                    b.HasOne("FoodStore_mvc.Models.FoodStore.Product", "Product")
                        .WithMany("ProductInvoiceWithQuantity")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ProductIn__produ__38996AB5");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.ProductPurchaseOrder", b =>
                {
                    b.HasOne("FoodStore_mvc.Models.FoodStore.PurchaseOrder", "PoNumNavigation")
                        .WithMany("ProductPurchaseOrder")
                        .HasForeignKey("PoNum")
                        .HasConstraintName("FK__ProductPu__po_nu__403A8C7D");

                    b.HasOne("FoodStore_mvc.Models.FoodStore.Product", "Product")
                        .WithMany("ProductPurchaseOrder")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ProductPu__produ__3F466844");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.PurchaseOrder", b =>
                {
                    b.HasOne("FoodStore_mvc.Models.FoodStore.Store", "BranchNavigation")
                        .WithMany("PurchaseOrder")
                        .HasForeignKey("Branch")
                        .HasConstraintName("FK__PurchaseO__branc__3C69FB99");
                });

            modelBuilder.Entity("FoodStore_mvc.Models.FoodStore.Store", b =>
                {
                    b.HasOne("FoodStore_mvc.Models.FoodStore.Building", "Building")
                        .WithMany("Store")
                        .HasForeignKey("BuildingName", "UnitNum")
                        .HasConstraintName("FK__Store__2F10007B");
                });
#pragma warning restore 612, 618
        }
    }
}
